services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./radarr_config:/config
      - /usr/local/datarr/downloads:/radarr/downloads
      - /usr/local/datarr/content:/radarr/movies
    ports:
      - 7878:7878

    healthcheck:
      test: nc -z localhost ${PORT} || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    restart: unless-stopped
